add manifestos k8s
g12-4soat/techmedicos-api pull request #5
Opened 2024-07-20 15:49 UTC by vitor-lupinetti

#4

2024-07-20 16:01 UTC, gabriellima09 requested changes

2024-07-20 16:01 UTC, gabriellima09 commented on k8s/deployments/techmedicos-api-deployment.yaml
> +            - containerPort: 80
Trocar pra Porta 8080

2024-07-20 16:01 UTC, gabriellima09 commented on k8s/deployments/techmedicos-api-deployment.yaml
> +      targetPort: 80
Trocar pra Porta 8080

2024-07-20 16:01 UTC, gabriellima09 commented on k8s/deployments/techmedicos-api-deployment.yaml
> +              port: 80
Trocar pra Porta 8080

2024-07-20 16:01 UTC, gabriellima09 commented on k8s/deployments/techmedicos-api-deployment.yaml
> +              port: 80
Trocar pra Porta 8080

2024-07-20 17:10 UTC, nsosoares approved these changes

2024-07-22 23:40 UTC, gabriellima09 approved these changes

2024-07-23 00:08 UTC, merged